### ISSUE TITLE
Better code

### ISSUE THREAD

**Issue by bacloud14** [bacloud14/exec#3]
Code refactoring:
The purpose is to reduced complexity and improve source-code maintainability. 
Better use of small functions in a modular programming style.

**Comment by BashCache** [comment]
Can I claim this?

**Comment by bacloud14** [comment]
Oh yes, it is the purpose.
Many thanks 👍

**Comment by BashCache** [comment]
Please help me in resolving the error!
I am not able to do: npm install eslint
It says: Please include the following file:
 /exec/npm-debug.log

**Comment by bacloud14** [comment]
Eslint is not part of the package. However if you try to use it , try to install it in the general scope. npm install -g eslint 
Otherwise I don't know about this particular error so sorry

**Comment by bacloud14** [comment]
Try to see the log as suggested
